#!/usr/bin/env bash
#
# tests/docsurfaces.sh — Textual invariants over the hand-authored doc surfaces.
#
# WHAT THIS FILE DOES
#   Three sweeps over README.md, WORKFLOW.md, docs/features/*.md and the skill
#   bodies. There is no script under test; the invariants are textual ones over
#   a corpus, like tests/scripthygiene.sh.
#
#   WHY THESE THREE. A doc-retirement pass in this project verified itself by
#   running two per-script test suites. Both passed, and both were the wrong
#   question: a retirement's real risk is the omission class — a surviving
#   mention somewhere else in the tree — which no per-script suite can see.
#
#   The correction has to be two checks, not one, because they fail in opposite
#   directions and neither sees the other's failure:
#
#     RETIREMENT — a symbol the code no longer has must not survive in prose.
#       Caught by sweeping for the dead name.
#     INTRODUCTION — a verb the code gained must appear where verbs are
#       enumerated. A "carries no occurrence of any retired symbol" check is
#       structurally incapable of noticing a MISSING one, which is how a shipped
#       verb stayed absent from an operator-facing surface entirely while every
#       retirement check passed.
#
#   The third sweep is for dead in-page anchors, which is how a fix to one
#   surface silently broke another: renaming a heading to include a new verb
#   left the link pointing at the old anchor.
#
#   Fail-closed: every sweep asserts it enumerated a non-empty corpus, so a
#   mis-resolved $REPO_ROOT fails loudly rather than passing vacuously.
#
# HOW TO RUN
#   bash tests/docsurfaces.sh              # standalone
#   bash skills/meta-test/scripts/run.sh   # via the aggregate runner
#
# CONVENTIONS: see skills/meta-test/scripts/testlib.sh header.

set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$(cd "$HERE/../skills/meta-test/scripts" && pwd)/testlib.sh"

# ─── Section: Helpers ────────────────────────────────────────────────────────

# doc_corpus — the hand-authored surfaces, one path per line. ARCHITECTURE.md is
# deliberately absent: it is regenerated by /jim:arch rather than hand-edited,
# and it carries retirement annotations ("retired in <spec>") on purpose, so a
# retired name living there is a record rather than drift. docs/notes,
# docs/issues and docs/specs are absent for the same reason — they are history.
doc_corpus() {
  local f
  for f in "$REPO_ROOT"/README.md "$REPO_ROOT"/WORKFLOW.md \
           "$REPO_ROOT"/docs/features/*.md \
           "$REPO_ROOT"/skills/*/SKILL.md \
           "$REPO_ROOT"/skills/*/references/*.md; do
    [[ -e "$f" ]] && printf '%s\n' "$f"
  done
}

# ledger_verbs — every verb jimledger.sh dispatches, one per line.
ledger_verbs() {
  sed -n '/^  case "\$sub" in/,/^  esac/p' "$REPO_ROOT/skills/ledger/scripts/jimledger.sh" \
    | sed -n 's/^    \([a-z][a-z-]*\)).*/\1/p'
}

# gh_anchor <heading-text> — the GitHub in-page anchor for a heading: lowercase,
# drop every byte that is not a letter, digit, space or hyphen, then spaces to
# hyphens. A space-surrounded dropped character therefore yields a double hyphen,
# which is exactly the case that made the live link dead.
gh_anchor() {
  printf '%s\n' "$1" \
    | LC_ALL=C tr '[:upper:]' '[:lower:]' \
    | sed 's/[^a-z0-9 -]//g' \
    | tr ' ' '-'
}

# ─── Section: Cases ──────────────────────────────────────────────────────────

# RETIREMENT. Each symbol below was removed from the code; a surviving mention in
# an operator- or model-facing surface instructs someone to call something that
# is gone. `mv-spec` is matched with a trailing guard because `mv-spec-id` is
# live — the near-miss is the whole reason to spell the pattern rather than the
# name.
case_docsurfaces_retired_symbols_are_gone() {
  local -a retired=('vacated-max' 'is_prov_basename' 'mv-spec[^-]' 'next-id spec')
  local sym n=0 f hits
  while IFS= read -r f; do n=$((n + 1)); done < <(doc_corpus)
  assert_eq "the doc corpus enumerated (>= 10, got $n)" "yes" \
    "$([[ "$n" -ge 10 ]] && echo yes || echo no)"
  for sym in "${retired[@]}"; do
    hits=""
    while IFS= read -r f; do
      grep -qE -- "$sym" "$f" && hits="$hits${f#"$REPO_ROOT"/} "
    done < <(doc_corpus)
    assert_eq "no surface still names the retired '$sym'" "" "${hits% }"
  done
}

# INTRODUCTION, ledger half. Every verb the script dispatches is named in the
# feature doc that enumerates them, so a new verb cannot ship undocumented.
case_docsurfaces_ledger_verbs_are_documented() {
  local doc="$REPO_ROOT/docs/features/ledger.md" v n=0 missing=""
  while IFS= read -r v; do
    [[ -n "$v" ]] || continue
    n=$((n + 1))
    grep -qF -- "\`$v\`" "$doc" || missing="$missing$v "
  done < <(ledger_verbs)
  assert_eq "the dispatch table was read (>= 15 verbs, got $n)" "yes" \
    "$([[ "$n" -ge 15 ]] && echo yes || echo no)"
  assert_eq "every dispatched ledger verb is documented" "" "${missing% }"
}

# INTRODUCTION, allocator half. The three hand-run registry verbs are described
# on two operator-facing surfaces plus the feature doc for the system that uses
# them. A fourth verb, or a fourth surface, has to be added everywhere or fail
# here — which is the check that did not exist when one of these shipped and
# stayed absent from an operator surface entirely.
case_docsurfaces_registry_verbs_reach_every_surface() {
  # The two operator surfaces carry all three hand-run registry verbs. The
  # blueprint feature doc carries only the two the partition story binds on —
  # `sweep` and `catch-up` repair the registry generally and belong on the
  # operator surfaces, not in a document about groups.
  local -a verbs=('sweep' 'catch-up' 'lift')
  local -a surfaces=("README.md" "WORKFLOW.md")
  local v s missing=""
  for v in "${verbs[@]}"; do
    for s in "${surfaces[@]}"; do
      [[ -e "$REPO_ROOT/$s" ]] || { missing="$missing$s(absent) "; continue; }
      # Matched as a TABLE ROW, not as a substring anywhere in the file. Both
      # surfaces describe these verbs twice — once in a table, once in prose —
      # and a substring check is satisfied by either, so it cannot see a row
      # go missing while the prose still mentions the verb.
      grep -qE "^\| *\`jimalloc\.sh $v" "$REPO_ROOT/$s" || missing="$missing$s:$v "
    done
  done
  for v in 'partition-batch' 'lift'; do
    grep -qF -- "$v" "$REPO_ROOT/docs/features/blueprints.md" \
      || missing="$missing docs/features/blueprints.md:$v"
  done
  assert_eq "every registry verb reaches every operator surface" "" "${missing% }"
  # The prose count and the table rows are two statements of one fact, and the
  # count is the half that silently goes stale when a row is added.
  assert_eq "README states the verb count it lists" "1" \
    "$(grep -c 'Three registry-integrity verbs' "$REPO_ROOT/README.md")"
}

# Dead in-page anchors. A link to `#foo` in a file with no heading yielding
# `foo` is broken, and renaming a heading is exactly how one gets that way.
case_docsurfaces_internal_anchors_resolve() {
  local f rel n=0 target broken="" heads
  while IFS= read -r f; do
    n=$((n + 1))
    rel="${f#"$REPO_ROOT"/}"
    heads="$(sed -n 's/^#\{1,6\}[[:space:]]\+//p' "$f" | while IFS= read -r h; do gh_anchor "$h"; done)"
    while IFS= read -r target; do
      [[ -n "$target" ]] || continue
      printf '%s\n' "$heads" | grep -qx -- "$target" || broken="$broken$rel#$target "
    done < <(grep -oE '\]\(#[^)]+\)' "$f" | sed 's/^](#//; s/)$//')
  done < <(doc_corpus)
  assert_eq "the doc corpus enumerated (>= 10, got $n)" "yes" \
    "$([[ "$n" -ge 10 ]] && echo yes || echo no)"
  assert_eq "every in-page anchor resolves to a heading" "" "${broken% }"
}

# INTRODUCTION, placement half. The scrub moment that survives auto-filing under
# a branch placement is decided by the emitter, so §7a's job is to say so and to
# name the flag that reaches it. Asserting only that the rule is *stated* was the
# original mistake here: it certified the property that did not matter while no
# consumer executed the rule at all. The companion case below is the one that
# checks the consumers.
case_docsurfaces_placement_scrub_rule_is_stated() {
  local skill="$REPO_ROOT/skills/issue/SKILL.md" body
  assert_eq "the issue skill is present" "yes" \
    "$([[ -r "$skill" ]] && echo yes || echo no)"
  body="$(sed -n '/^### 7a\./,/^### 8\./p' "$skill")"
  assert_eq "the candidate-batch section was located" "yes" \
    "$([[ -n "$body" ]] && echo yes || echo no)"
  assert_match "names the auto-file key"      'auto_issue_file'     "$body"
  assert_match "names the placement key"      'issue_placement'     "$body"
  assert_match "names the acknowledgement"    'issue_placement_ack' "$body"
  assert_match "states the degrade"           'degrade'             "$body"
  assert_match "names the flag that carries it" '\-\-auto'          "$body"
  assert_match "names the code it answers with" 'exit'              "$body"
}

# The consumers half — the property that actually matters. The emitter can only
# apply the gate when the caller passes `--auto`, so that flag is the whole
# coupling, and a surfacing skill that auto-files without it publishes an
# unreviewed batch to a shared branch silently. The consumer set is swept rather
# than listed, so a skill added later inherits the check instead of missing it.
case_docsurfaces_auto_file_consumers_pass_the_gate_flag() {
  local f name n=0 missing="" unhandled=""
  while IFS= read -r f; do
    name="${f#"$REPO_ROOT"/skills/}"; name="${name%/SKILL.md}"
    [[ "$name" == "issue" ]] && continue
    n=$(( n + 1 ))
    grep -q 'new\.sh \[\?--auto' "$f" || missing+="$name "
    grep -q 'exit code 4'        "$f" || unhandled+="$name "
  done < <(grep -rl 'auto_issue_file' "$REPO_ROOT"/skills/*/SKILL.md 2>/dev/null)
  # Without this the sweep passes vacuously on a glob that matched nothing.
  assert_eq "the consumer set was found (>= 8, got $n)" "yes" \
    "$([[ "$n" -ge 8 ]] && echo yes || echo no)"
  assert_eq "every auto-filing skill passes --auto"      "" "${missing% }"
  assert_eq "every auto-filing skill handles the refusal" "" "${unhandled% }"
}

# The two-phase edit door has to stay documented where an agent editing an issue
# will look, or a placement-configured project silently edits a file that is not
# the collection.
case_docsurfaces_placement_edit_flow_is_stated() {
  local skill="$REPO_ROOT/skills/issue/SKILL.md" body
  body="$(sed -n '/^### 6a\./,/^### 7\./p' "$skill")"
  assert_eq "the edit-convention section was located" "yes" \
    "$([[ -n "$body" ]] && echo yes || echo no)"
  assert_match "names begin"  'place\.sh begin'  "$body"
  assert_match "names commit" 'place\.sh commit' "$body"
  assert_match "names abort"  'place\.sh abort'  "$body"
}

# ─── Section: Standalone-runnable tail ───────────────────────────────────────

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  FILTER="${1:-}"
  run_discovered_cases
fi
