#!/usr/bin/env bash
#
# tests/docsurfaces.sh — Textual invariants over the hand-authored doc surfaces.
#
# WHAT THIS FILE DOES
#   Three sweeps over README.md, WORKFLOW.md, docs/features/*.md and the skill
#   bodies. There is no script under test; the invariants are textual ones over
#   a corpus, like tests/scripthygiene.sh.
#
#   WHY THESE THREE. A doc-retirement pass in this project verified itself by
#   running two per-script test suites. Both passed, and both were the wrong
#   question: a retirement's real risk is the omission class — a surviving
#   mention somewhere else in the tree — which no per-script suite can see.
#
#   The correction has to be two checks, not one, because they fail in opposite
#   directions and neither sees the other's failure:
#
#     RETIREMENT — a symbol the code no longer has must not survive in prose.
#       Caught by sweeping for the dead name.
#     INTRODUCTION — a verb the code gained must appear where verbs are
#       enumerated. A "carries no occurrence of any retired symbol" check is
#       structurally incapable of noticing a MISSING one, which is how a shipped
#       verb stayed absent from an operator-facing surface entirely while every
#       retirement check passed.
#
#   The third sweep is for dead in-page anchors, which is how a fix to one
#   surface silently broke another: renaming a heading to include a new verb
#   left the link pointing at the old anchor.
#
#   Fail-closed: every sweep asserts it enumerated a non-empty corpus, so a
#   mis-resolved $REPO_ROOT fails loudly rather than passing vacuously.
#
# HOW TO RUN
#   bash tests/docsurfaces.sh              # standalone
#   bash skills/meta-test/scripts/run.sh   # via the aggregate runner
#
# CONVENTIONS: see skills/meta-test/scripts/testlib.sh header.

set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$(cd "$HERE/../skills/meta-test/scripts" && pwd)/testlib.sh"

# ─── Section: Helpers ────────────────────────────────────────────────────────

# doc_corpus — the hand-authored surfaces, one path per line. ARCHITECTURE.md is
# deliberately absent: it is regenerated by /jim:arch rather than hand-edited,
# and it carries retirement annotations ("retired in <spec>") on purpose, so a
# retired name living there is a record rather than drift. docs/notes,
# docs/issues and docs/specs are absent for the same reason — they are history.
doc_corpus() {
  local f
  for f in "$REPO_ROOT"/README.md "$REPO_ROOT"/WORKFLOW.md \
           "$REPO_ROOT"/docs/features/*.md \
           "$REPO_ROOT"/skills/*/SKILL.md \
           "$REPO_ROOT"/skills/*/references/*.md; do
    [[ -e "$f" ]] && printf '%s\n' "$f"
  done
}

# ledger_verbs — every verb jimledger.sh dispatches, one per line.
ledger_verbs() {
  sed -n '/^  case "\$sub" in/,/^  esac/p' "$REPO_ROOT/skills/ledger/scripts/jimledger.sh" \
    | sed -n 's/^    \([a-z][a-z-]*\)).*/\1/p'
}

# migration_subcommands <script> — every subcommand the script advertises in its
# own usage text, one per line.
#
#   Read from usage() rather than the dispatch table on purpose. The dispatch
#   also carries an internal primitive the script deliberately does not
#   advertise, and what an operator is told exists is exactly what the feature
#   doc owes a row — so an unadvertised primitive is correctly outside this set,
#   and adding it to usage() pulls it in without anyone editing this list.
migration_subcommands() {
  local base; base="$(basename "$1")"
  sed -n "s/^ *'  bash $base \([a-z][a-z-]*\).*/\1/p" "$1" | LC_ALL=C sort -u
}

# conf_documented <key> <file> — 0 when <file>'s tables name <key>.
#
#   Three shapes are accepted, because all three are how the tables are actually
#   written: the CLI name as a row, the TOML name (`<key>_path`, the suffix the
#   resolver adds for path-valued keys) as a row, and a family row such as
#   `health_threshold_<signal>` whose text names this key's own suffix in
#   backticks. Demanding a row per key would ask the tables to stop documenting
#   a five-key family in one line, which is a worse document, not a better one.
conf_documented() {
  local key="$1" file="$2" prefix suffix
  grep -qE "^\| \`($key|${key}_path)\`" "$file" && return 0
  # A family row documents several keys at once: its first cell carries a
  # `<placeholder>` tail and its text names each member's own suffix. The
  # prefixes are read out of the document rather than guessed by splitting the
  # key, because a member's suffix can itself carry an underscore.
  while IFS= read -r prefix; do
    [[ "$key" == "$prefix"_* ]] || continue
    suffix="${key#"${prefix}_"}"
    grep -qE "^\| \`${prefix}_<[a-z]+>\`.*\`$suffix\`" "$file" && return 0
  done < <(sed -n 's/^| `\([a-z_]*\)_<[a-z]*>`.*/\1/p' "$file" | LC_ALL=C sort -u)
  return 1
}

# gh_anchor <heading-text> — the GitHub in-page anchor for a heading: lowercase,
# drop every byte that is not a letter, digit, space or hyphen, then spaces to
# hyphens. A space-surrounded dropped character therefore yields a double hyphen,
# which is exactly the case that made the live link dead.
gh_anchor() {
  printf '%s\n' "$1" \
    | LC_ALL=C tr '[:upper:]' '[:lower:]' \
    | sed 's/[^a-z0-9 -]//g' \
    | tr ' ' '-'
}

# ─── Section: Cases ──────────────────────────────────────────────────────────

# RETIREMENT. Each symbol below was removed from the code; a surviving mention in
# an operator- or model-facing surface instructs someone to call something that
# is gone. `mv-spec` is matched with a trailing guard because `mv-spec-id` is
# live — the near-miss is the whole reason to spell the pattern rather than the
# name.
case_docsurfaces_retired_symbols_are_gone() {
  local -a retired=('vacated-max' 'is_prov_basename' 'mv-spec[^-]' 'next-id spec')
  local sym n=0 f hits
  while IFS= read -r f; do n=$((n + 1)); done < <(doc_corpus)
  assert_eq "the doc corpus enumerated (>= 10, got $n)" "yes" \
    "$([[ "$n" -ge 10 ]] && echo yes || echo no)"
  for sym in "${retired[@]}"; do
    hits=""
    while IFS= read -r f; do
      grep -qE -- "$sym" "$f" && hits="$hits${f#"$REPO_ROOT"/} "
    done < <(doc_corpus)
    assert_eq "no surface still names the retired '$sym'" "" "${hits% }"
  done
}

# transition_verbs — every lifecycle verb transition.sh dispatches, one per
# line, read from the array it validates against.
#
#   Derived rather than retyped. A list written into this file would have the
#   defect it exists to catch: a verb added to the script but not to the list
#   passes a check whose whole purpose is that class.
#   The closing paren is found with awk rather than a sed range, because a sed
#   range does not test its end pattern on the start line — against a
#   single-line array it would run on to the next paren in the file.
transition_verbs() {
  awk -v pfx="readonly TRANSITION_VERBS=(" '
    substr($0, 1, length(pfx)) == pfx { inside = 1; $0 = substr($0, length(pfx) + 1) }
    inside {
      if (match($0, /\)/)) { print substr($0, 1, RSTART - 1); exit }
      print
    }
  ' "$REPO_ROOT/skills/issue/scripts/transition.sh" \
    | tr -s '[:space:]' '\n' | grep -v '^$'
}

# INTRODUCTION, lifecycle half. The verbs are restated in prose on four
# hand-maintained operator surfaces, and only ARCHITECTURE.md is refreshed by
# the pipeline. A hand edit fixes the increment that noticed the drift and
# leaves the next one exposed, so the enumeration is checked rather than
# corrected. The feature doc is on the list because it is the doc for exactly
# the verbs this check derives, and it is the surface that went stale when two
# were added -- the sweep quantified over every surface but that one.
case_docsurfaces_transition_verbs_are_documented() {
  local v n=0 missing="" surface
  while IFS= read -r v; do
    [[ -n "$v" ]] || continue
    n=$((n + 1))
    for surface in "$REPO_ROOT/README.md" "$REPO_ROOT/WORKFLOW.md" \
                   "$REPO_ROOT/skills/issue/SKILL.md" \
                   "$REPO_ROOT/docs/features/issues.md"; do
      # The verb, then a space or its closing backtick. A surface documenting
      # it with operands -- `join <id> <umbrella>`, the feature doc's form --
      # counts, while `claimed-by` and `closed` still do not, because the
      # character after the verb decides it.
      grep -qE -- '`'"$v"'[ `]' "$surface" \
        || missing="$missing$(basename "$surface"):$v "
    done
  done < <(transition_verbs)
  assert_eq "the array was read (>= 7 verbs, got $n)" "yes" \
    "$([[ "$n" -ge 7 ]] && echo yes || echo no)"
  assert_eq "every dispatched lifecycle verb is documented" "" "${missing% }"
}

# INTRODUCTION, ledger half. Every verb the script dispatches is named in the
# feature doc that enumerates them, so a new verb cannot ship undocumented.
case_docsurfaces_ledger_verbs_are_documented() {
  local doc="$REPO_ROOT/docs/features/ledger.md" v n=0 missing=""
  while IFS= read -r v; do
    [[ -n "$v" ]] || continue
    n=$((n + 1))
    grep -qF -- "\`$v\`" "$doc" || missing="$missing$v "
  done < <(ledger_verbs)
  assert_eq "the dispatch table was read (>= 15 verbs, got $n)" "yes" \
    "$([[ "$n" -ge 15 ]] && echo yes || echo no)"
  assert_eq "every dispatched ledger verb is documented" "" "${missing% }"
}

# INTRODUCTION, allocator half. The three hand-run registry verbs are described
# on two operator-facing surfaces plus the feature doc for the system that uses
# them. A fourth verb, or a fourth surface, has to be added everywhere or fail
# here — which is the check that did not exist when one of these shipped and
# stayed absent from an operator surface entirely.
case_docsurfaces_registry_verbs_reach_every_surface() {
  # The two operator surfaces carry all three hand-run registry verbs. The
  # blueprint feature doc carries only the two the partition story binds on —
  # `sweep` and `catch-up` repair the registry generally and belong on the
  # operator surfaces, not in a document about groups.
  local -a verbs=('sweep' 'catch-up' 'lift')
  local -a surfaces=("README.md" "WORKFLOW.md")
  local v s missing=""
  for v in "${verbs[@]}"; do
    for s in "${surfaces[@]}"; do
      [[ -e "$REPO_ROOT/$s" ]] || { missing="$missing$s(absent) "; continue; }
      # Matched as a TABLE ROW, not as a substring anywhere in the file. The
      # table is the surface each operator scans for the verb; WORKFLOW.md also
      # names all three in prose, and a substring check is satisfied by that
      # prose alone, so it cannot see a row go missing.
      grep -qE "^\| *\`jimalloc\.sh $v" "$REPO_ROOT/$s" || missing="$missing$s:$v "
    done
  done
  for v in 'partition-batch' 'lift'; do
    grep -qF -- "$v" "$REPO_ROOT/docs/features/blueprints.md" \
      || missing="$missing docs/features/blueprints.md:$v"
  done
  assert_eq "every registry verb reaches every operator surface" "" "${missing% }"
  # The prose count and the table rows are two statements of one fact, and the
  # count is the half that silently goes stale when a row is added.
  assert_eq "README states the verb count it lists" "1" \
    "$(grep -c 'Three registry-integrity verbs' "$REPO_ROOT/README.md")"
}

# Dead in-page anchors. A link to `#foo` in a file with no heading yielding
# `foo` is broken, and renaming a heading is exactly how one gets that way.
case_docsurfaces_internal_anchors_resolve() {
  local f rel n=0 target broken="" heads
  while IFS= read -r f; do
    n=$((n + 1))
    rel="${f#"$REPO_ROOT"/}"
    heads="$(sed -n 's/^#\{1,6\}[[:space:]]\+//p' "$f" | while IFS= read -r h; do gh_anchor "$h"; done)"
    while IFS= read -r target; do
      [[ -n "$target" ]] || continue
      printf '%s\n' "$heads" | grep -qx -- "$target" || broken="$broken$rel#$target "
    done < <(grep -oE '\]\(#[^)]+\)' "$f" | sed 's/^](#//; s/)$//')
  done < <(doc_corpus)
  assert_eq "the doc corpus enumerated (>= 10, got $n)" "yes" \
    "$([[ "$n" -ge 10 ]] && echo yes || echo no)"
  assert_eq "every in-page anchor resolves to a heading" "" "${broken% }"
}

# INTRODUCTION, placement half. The scrub moment that survives auto-filing under
# a branch placement is decided by the emitter, so §7a's job is to say so and to
# name the flag that reaches it. Asserting only that the rule is *stated* was the
# original mistake here: it certified the property that did not matter while no
# consumer executed the rule at all. The companion case below is the one that
# checks the consumers.
case_docsurfaces_placement_scrub_rule_is_stated() {
  local skill="$REPO_ROOT/skills/issue/SKILL.md" body
  assert_eq "the issue skill is present" "yes" \
    "$([[ -r "$skill" ]] && echo yes || echo no)"
  body="$(sed -n '/^### 7a\./,/^### 8\./p' "$skill")"
  assert_eq "the candidate-batch section was located" "yes" \
    "$([[ -n "$body" ]] && echo yes || echo no)"
  assert_match "names the auto-file key"      'auto_issue_file'     "$body"
  assert_match "names the placement key"      'issue_placement'     "$body"
  assert_match "names the acknowledgement"    'issue_placement_ack' "$body"
  assert_match "states the degrade"           'degrade'             "$body"
  assert_match "names the flag that carries it" '[-][-]auto'        "$body"
  assert_match "names its counterpart"          '[-][-]reviewed'    "$body"
  assert_match "names the code it answers with" 'exit'              "$body"
}

# The § 7a roster, held to the grant rather than to a number. Three rosters
# disagreed with each other and with the canonical one, and a fourth consumer
# (the blueprint surface) was in none of them — because a count in prose goes
# stale the moment a consumer accrues, and nothing mechanical noticed. The
# consumer set has a mechanical definition: a skill that can invoke the emitter
# is one that files through the contract. Derive it and require § 7a to name
# every member, so the next consumer to accrue fails here instead of silently
# widening the gap.
case_docsurfaces_candidate_batch_roster_matches_the_grant() {
  local skill="$REPO_ROOT/skills/issue/SKILL.md" body f name missing="" n=0
  body="$(sed -n '/^### 7a\./,/^### 8\./p' "$skill")"
  assert_eq "the candidate-batch section was located" "yes" \
    "$([[ -n "$body" ]] && echo yes || echo no)"
  while IFS= read -r f; do
    name="${f#"$REPO_ROOT"/skills/}"; name="${name%/SKILL.md}"
    # The issue skill owns the contract and the interactive `add` verb; it is
    # the emitter's home, not one of its consumers.
    [[ "$name" == "issue" ]] && continue
    n=$(( n + 1 ))
    grep -q "/jim:$name" <<< "$body" || missing+="$name "
  done < <(grep -l 'scripts/new\.sh \*' "$REPO_ROOT"/skills/*/SKILL.md 2>/dev/null)
  # Without a floor the sweep passes vacuously on a glob that matched nothing.
  assert_eq "the consumer set was found (>= 11, got $n)" "yes" \
    "$([[ "$n" -ge 11 ]] && echo yes || echo no)"
  assert_eq "every skill granted the emitter is named in § 7a" "" "${missing% }"
  # And no fixed count is restated, which is what rotted three of these rosters.
  assert_eq "the roster states no fixed count" "" \
    "$(grep -oE '\b(seven|eight|nine|ten|eleven|twelve) surfacing skills' <<< "$body")"
}

# A partition migration does not route its issue-collection re-points — routing
# them would split jimledger.sh's fixed two-commit choreography, which is a
# partition-spec invariant. What it must not do is stay silent: a run that edits
# a stale checkout fork, or matches nothing and reports zero touched, is the
# staleness the placement exists to prevent. So the methodology has to state the
# skip AND say where the disclosure is read from, and the grant has to stay
# read-only — a write verb here would be the routing that was rejected.
case_docsurfaces_partition_discloses_unapplied_issue_repoints() {
  local m="$REPO_ROOT/skills/partition/references/partition-methodology.md"
  local s="$REPO_ROOT/skills/partition/SKILL.md" body tools
  assert_eq "the methodology is present" "yes" \
    "$([[ -r "$m" ]] && echo yes || echo no)"
  body="$(cat "$m")"
  assert_match "names the placement key"        'issue_placement'   "$body"
  assert_match "names the mode verb it asks"    'place\.sh mode'    "$body"
  assert_match "reads the real collection"      'begin --read'      "$body"
  assert_match "and releases the handle"        'place\.sh abort'   "$body"
  assert_match "states the skip in the gate"    'UNAPPLIED'         "$body"
  assert_match "names the constraint behind it" 'commit-split'      "$body"

  tools="$(sed -n '/^allowed-tools:/p' "$s")"
  assert_match "grants the read handle" 'place\.sh begin --read' "$tools"
  assert_match "grants the release"     'place\.sh abort'        "$tools"
  # The decision was out-of-scope-for-the-write. A publish verb in this grant is
  # that decision reversed by accident.
  assert_eq "grants no publish verb" "" \
    "$(grep -oE 'place\.sh (commit|run)' <<< "$tools")"
}

# The interactive half of the declaration. Under a placement the emitter refuses
# a filing that declares neither --auto nor --reviewed, so a consumer whose
# interactive path still calls the bare emitter is broken at exactly the moment
# a team configuration is adopted. Swept rather than listed, like the auto half.
case_docsurfaces_interactive_paths_declare_reviewed() {
  local f name missing="" n=0
  while IFS= read -r f; do
    name="${f#"$REPO_ROOT"/skills/}"; name="${name%/SKILL.md}"
    [[ "$name" == "issue" ]] && continue
    n=$(( n + 1 ))
    # References count: the blueprint surface keeps its emitter calls there.
    grep -rq -- 'new\.sh --reviewed' "$(dirname "$f")" || missing+="$name "
  done < <(grep -l 'scripts/new\.sh \*' "$REPO_ROOT"/skills/*/SKILL.md 2>/dev/null)
  assert_eq "the consumer set was found (>= 11, got $n)" "yes" \
    "$([[ "$n" -ge 11 ]] && echo yes || echo no)"
  assert_eq "every consumer declares a reviewed filing" "" "${missing% }"
}

# The consumers half — the property that actually matters. The emitter can only
# apply the gate when the caller passes `--auto`, so that flag is the whole
# coupling, and a surfacing skill that auto-files without it publishes an
# unreviewed batch to a shared branch silently. The consumer set is swept rather
# than listed, so a skill added later inherits the check instead of missing it.
#
# The sweep is scoped to each skill's auto-file branch rather than to its file.
# A file-scoped grep is satisfied by a `--auto` sitting on the *interactive*
# emitter call — the one path where the flag would be wrong — while the quiet
# path omits it, which is the arrangement that publishes. Scoping needs the
# branch to be findable, which is why all nine open it the same way.
case_docsurfaces_auto_file_consumers_pass_the_gate_flag() {
  local f name n=0 unscoped="" missing="" unhandled="" nofallback="" branch
  while IFS= read -r f; do
    name="${f#"$REPO_ROOT"/skills/}"; name="${name%/SKILL.md}"
    [[ "$name" == "issue" ]] && continue
    n=$(( n + 1 ))
    branch="$(sed -n '/^ *IF auto_issue_file == "true" THEN/,/INTERACTIVE PATH/p' "$f")"
    if [[ -z "$branch" ]]; then
      unscoped+="$name "
      continue
    fi
    grep -q 'new\.sh --auto' <<< "$branch" || missing+="$name "
    grep -q 'exit code 4'    <<< "$branch" || unhandled+="$name "
    # The refusal is a redirection, so the path it redirects to has to exist.
    grep -q 'INTERACTIVE PATH' "$f" || nofallback+="$name "
  done < <(grep -rl 'auto_issue_file' "$REPO_ROOT"/skills/*/SKILL.md 2>/dev/null)
  # Without this the sweep passes vacuously on a glob that matched nothing, and
  # a floor below the real count lets one skill leave the set silently.
  assert_eq "the consumer set was found (>= 9, got $n)" "yes" \
    "$([[ "$n" -ge 9 ]] && echo yes || echo no)"
  assert_eq "every auto-filing skill has a findable auto-file branch" "" "${unscoped% }"
  assert_eq "every auto-file branch passes --auto"          "" "${missing% }"
  assert_eq "every auto-file branch handles the refusal"    "" "${unhandled% }"
  assert_eq "every refusal has an interactive path to fall to" "" "${nofallback% }"
}

# The two-phase edit door has to stay documented where an agent editing an issue
# will look, or a placement-configured project silently edits a file that is not
# the collection.
case_docsurfaces_placement_edit_flow_is_stated() {
  local skill="$REPO_ROOT/skills/issue/SKILL.md" body
  body="$(sed -n '/^### 6a\./,/^### 7\./p' "$skill")"
  assert_eq "the edit-convention section was located" "yes" \
    "$([[ -n "$body" ]] && echo yes || echo no)"
  assert_match "names begin"  'place\.sh begin'  "$body"
  assert_match "names commit" 'place\.sh commit' "$body"
  assert_match "names abort"  'place\.sh abort'  "$body"
}

# A close sets every field a reader would check and can still omit the only half
# that cannot be re-derived. The convention was documented in the retrospective
# notes for two rounds while four issues closed without one, which is the case
# for pinning it at the point of use instead: the dispatch bullet an executor
# reads, and the checklist it applies literally. Both, because a rule stated
# once in prose is a rule the checklist does not enforce.
case_docsurfaces_close_records_its_resolution() {
  local skill="$REPO_ROOT/skills/issue/SKILL.md" bullet checklist
  bullet="$(sed -n '/^  - `close` finishes it\./,/^  - `reopen`/p' "$skill")"
  assert_eq "the close dispatch bullet was located" "yes" \
    "$([[ -n "$bullet" ]] && echo yes || echo no)"
  assert_match "the bullet names the section"   'Resolution' "$bullet"
  assert_match "and says it is unconditional"   'not conditional on the outcome' "$bullet"
  checklist="$(sed -n '/^For the transition verbs/,/^For the read verbs/p' "$skill")"
  assert_eq "the transition checklist was located" "yes" \
    "$([[ -n "$checklist" ]] && echo yes || echo no)"
  assert_match "the checklist checks it" 'Resolution' "$checklist"
}

# The insights analyst is handed a directory and is the collection's terminal
# reader, so a literal collection path in its method is not a stale mention —
# it is a second collection. Under a placement the roster and graph come from
# the materialized destination while `docs/issues/` in the working tree is a
# different set of bodies, and nothing downstream can notice the pairing.
case_docsurfaces_analyst_reads_the_directory_it_is_handed() {
  local agent="$REPO_ROOT/agents/issue-analyst.md" body
  assert_eq "the analyst is present" "yes" \
    "$([[ -r "$agent" ]] && echo yes || echo no)"
  body="$(cat "$agent")"
  assert_match "composes body paths from the handed directory" '<dir>/' "$body"
  assert_eq "and names no collection glob of its own" "no" \
    "$(grep -q 'docs/issues/\*' "$agent" && echo yes || echo no)"
}

# The same reasoning reaches past the skill. WORKFLOW.md is where a user is told
# how to close an issue, and it said to edit `status:` directly — which leaves
# `outcome` empty for the collection's own integrity check to report, and which
# under a placement edits something that is not the collection at all. Sweeping
# only the skill left the one sentence a user actually follows outside both
# guards. Scoped to the section rather than to one line, because the correction
# splits what was one sentence into a verb and a content-edit caveat.
case_docsurfaces_workflow_close_flow_survives_a_placement() {
  local wf="$REPO_ROOT/WORKFLOW.md" sec
  assert_eq "the workflow doc is present" "yes" \
    "$([[ -r "$wf" ]] && echo yes || echo no)"
  sec="$(awk '/^### Discovery capture/ { s=1; next }
              s && (/^## / || /^### /) { s=0 }
              s' "$wf")"
  assert_nonempty "the capture section was located" "$sec"
  assert_match "closing goes through the verb"     'close <id>'      "$sec"
  assert_match "which is what records the outcome" 'outcome'         "$sec"
  assert_match "the placement caveat survives"     'issue_placement' "$sec"
  assert_match "and points at the flow that works" '6a'              "$sec"
  # The instruction this replaced is what produced the record the index reports.
  assert_eq "nobody is sent to a hand-written close" "" \
    "$(grep -oE 'editing its .status:. field' <<< "$sec")"
}

# A skill's grant and its body are one document read by two readers. The body
# prescribed the lifecycle verbs and the collection conversions; the grant named
# neither script, so every documented step ended at a permission prompt for a
# script the skill itself had just told the developer to run. Swept rather than
# listed, so a call site added later is covered without anyone remembering to.
#
# The withheld half is load-bearing too. `migrate.sh prefix --apply` renames every
# file in the collection and rewrites its inbound references, and this body never
# instructs it — so the grant enumerates the two subcommands the body does use
# rather than taking the script whole.
case_docsurfaces_issue_grant_covers_the_scripts_it_instructs() {
  local s="$REPO_ROOT/skills/issue/SKILL.md" tools body scr n=0 missing=""
  assert_eq "the skill is present" "yes" \
    "$([[ -r "$s" ]] && echo yes || echo no)"
  tools="$(sed -n '/^allowed-tools:/p' "$s")"
  body="$(awk 'NR==1 && $0 == "---" { fm=1; next }
               fm && $0 == "---"    { fm=0; rest=1; next }
               rest' "$s")"
  for scr in $(printf '%s\n' "$body" | grep -o 'scripts/[a-z]*\.sh' | LC_ALL=C sort -u); do
    n=$(( n + 1 ))
    grep -qF "$scr" <<< "$tools" || missing="$missing ${scr#scripts/}"
  done
  assert_eq "the body names call sites at all" "yes" \
    "$([[ $n -gt 0 ]] && echo yes || echo no)"
  assert_eq "every script the body invokes is granted" "" "${missing# }"
  # The collection-wide rename is the verb this skill deliberately does not hold.
  assert_eq "and the collection-wide rename is not" "" \
    "$(grep -oE 'migrate\.sh prefix' <<< "$tools")"
}


# INTRODUCTION, migrations half. A migration subcommand the scripts advertise is
# a row in the doc that enumerates them, and every row names a subcommand that
# exists. Both directions, because they fail independently and neither sees the
# other: a shipped subcommand with no row, and a row outliving the subcommand it
# describes. Two subcommands shipped without reaching this table before the
# check existed.
case_docsurfaces_migration_commands_are_documented() {
  local doc="$REPO_ROOT/docs/features/issues.md"
  local script base sub n=0 missing="" stale=""
  for script in "$REPO_ROOT/skills/issue/scripts/migrate.sh" \
                "$REPO_ROOT/skills/issue/scripts/backfill.sh"; do
    base="$(basename "$script")"
    while IFS= read -r sub; do
      [[ -n "$sub" ]] || continue
      n=$((n + 1))
      grep -qE "^\| \`$base $sub" "$doc" || missing="$missing$base $sub, "
    done < <(migration_subcommands "$script")
    while IFS= read -r sub; do
      [[ -n "$sub" ]] || continue
      migration_subcommands "$script" | grep -qx -- "$sub" \
        || stale="$stale$base $sub, "
    done < <(sed -n "s/^| \`$base \([a-z][a-z-]*\).*/\1/p" "$doc" | LC_ALL=C sort -u)
  done
  assert_eq "both usage blocks were read (>= 5 subcommands, got $n)" "yes" \
    "$([[ "$n" -ge 5 ]] && echo yes || echo no)"
  assert_eq "every advertised migration subcommand has a row" "" "${missing%, }"
  assert_eq "every migration row names a subcommand that exists" "" "${stale%, }"
}

# INTRODUCTION, config half. Every key the resolver knows is named where keys are
# enumerated: both operator surfaces, and — for the two families the issue
# feature owns — its feature doc as well. A key shipped and reachable from a
# jimconf.toml nobody documents is configuration only its author knows about,
# which is how two of them shipped.
case_docsurfaces_config_keys_are_documented() {
  local k n=0 no_readme="" no_example="" no_feature=""
  while IFS= read -r k; do
    [[ -n "$k" ]] || continue
    n=$((n + 1))
    conf_documented "$k" "$REPO_ROOT/README.md" || no_readme="$no_readme$k "
    grep -qE "^#? *($k|${k}_path) *=" "$REPO_ROOT/jimconf.toml.example" \
      || no_example="$no_example$k "
    case "$k" in
      issue*|identity*)
        conf_documented "$k" "$REPO_ROOT/docs/features/issues.md" \
          || no_feature="$no_feature$k " ;;
    esac
  done < <(bash "$REPO_ROOT/skills/conf/scripts/jimconf.sh" keys)
  assert_eq "the key list was read (>= 40 keys, got $n)" "yes" \
    "$([[ "$n" -ge 40 ]] && echo yes || echo no)"
  assert_eq "every key reaches README's tables"          "" "${no_readme% }"
  assert_eq "every key reaches jimconf.toml.example"     "" "${no_example% }"
  assert_eq "every issue key reaches its feature doc"    "" "${no_feature% }"
}

# emitter_flags — every flag new.sh's parser accepts, one per line. Read off
# the case arms the loop dispatches on rather than the usage comment above
# them, so this is what the script does rather than what it says about itself.
emitter_flags() {
  awk '
    $0 == "while [[ $# -gt 0 ]]; do" { inside = 1; next }
    inside && $0 == "done" { exit }
    inside {
      if (substr($1, 1, 2) == "--") {
        p = index($1, ")")
        if (p > 0) print substr($1, 1, p - 1)
      }
    }
  ' "$REPO_ROOT/skills/issue/scripts/new.sh"
}

# capture_flag_excused <flag> — true when the documented capture flow passes
# this flag deliberately not at all, with the reason. Every flag emitter_flags
# discovers must be excused here or appear in the documented invocation, so a
# flag cannot enter the emitter without a decision about whether a capture may
# set it. The failure direction is what matters: a new flag is REQUIRED by
# default and has to be argued out, rather than being silently absent.
capture_flag_excused() {
  case "$1" in
    # The allocator resolves the identity at save time; the skill says so and
    # says not to pass either.
    --slug|--num)  return 0 ;;
    # Tests and the placement re-exec own these; a capture never names one.
    --dir|--place-token) return 0 ;;
    # A new capture is open, which is the emitter's own default.
    --status)      return 0 ;;
    # The confirm-or-edit moment IS the review, so this path is --reviewed.
    --auto)        return 0 ;;
    *) return 1 ;;
  esac
}

# skill_emitter_invocation — the fenced emitter call /jim:issue add documents,
# from the line naming the script through the last continued line. Anchored on
# the literal `--reviewed`, which is what tells the capture flow's invocation
# apart from the candidate batch's, whose declaration flag is a choice.
skill_emitter_invocation() {
  awk '
    index($0, "new.sh --reviewed") > 0 { on = 1 }
    on { print; if ($0 !~ /\\$/) exit }
  ' "$REPO_ROOT/skills/issue/SKILL.md"
}

# INTRODUCTION, capture half. The lifecycle verbs reach a user through a
# dispatch table this suite already checks; the capture flags reach one only
# through the emitter invocation the skill body spells out, and a flag the
# script gained but that invocation never passes is unreachable from the
# command however well the script implements it. That is how this increment's
# headline capability shipped with a flag surface nobody could type.
case_docsurfaces_capture_flags_reach_the_emitter_invocation() {
  local skill="$REPO_ROOT/skills/issue/SKILL.md" f n=0 missing="" unknown=""
  local invocation add_bullet
  invocation="$(skill_emitter_invocation)"
  assert_nonempty "the documented invocation was found" "$invocation"

  while IFS= read -r f; do
    [[ -n "$f" ]] || continue
    n=$((n + 1))
    capture_flag_excused "$f" && continue
    grep -qF -- "$f " <<< "$invocation" || missing="$missing$f "
  done < <(emitter_flags)
  assert_eq "the parser was read (>= 10 flags, got $n)" "yes" \
    "$([[ "$n" -ge 10 ]] && echo yes || echo no)"
  assert_eq "every capture flag reaches the documented invocation" "" \
    "${missing% }"

  # The other direction: a flag the documentation passes that the emitter does
  # not parse is refused at rc 2, so the whole filing fails.
  while IFS= read -r f; do
    [[ -n "$f" ]] || continue
    grep -qxF -- "$f" <(emitter_flags) || unknown="$unknown$f "
  done < <(grep -oE -- '--[a-z-]+' <<< "$invocation" | LC_ALL=C sort -u)
  assert_eq "and passes no flag the emitter would refuse" "" "${unknown% }"

  # Forwarding is half of it. The values a developer types arrive inside the
  # argument string, so the dispatch has to take them out of it before the
  # remainder becomes the capture subject -- otherwise the flags are filed as
  # part of the title.
  add_bullet="$(awk '/^- \*\*`claim`/ { exit } /^- \*\*`add`\*\*/ { on = 1 } on' "$skill")"
  assert_nonempty "the add dispatch bullet was found" "$add_bullet"
  assert_match "the dispatch names the kind flag" '`--type[ `]'    "$add_bullet"
  assert_match "and the membership flag"          '`--part-of[ `]' "$add_bullet"
}

# issue_kinds() — the kinds the emitter admits, read off its own array, the way
# transition_verbs reads the lifecycle vocabulary.
issue_kinds() {
  awk -v pfx="readonly ISSUE_TYPES=(" '
    substr($0, 1, length(pfx)) == pfx { inside = 1; $0 = substr($0, length(pfx) + 1) }
    inside {
      if (match($0, /\)/)) { print substr($0, 1, RSTART - 1); exit }
      print
    }
  ' "$REPO_ROOT/skills/issue/scripts/new.sh" \
    | tr -s '[:space:]' '\n' | grep -v '^$'
}

# INTRODUCTION, capture-kind half. The pre-write checklist restates the
# emitter's kind vocabulary in prose, and a checklist is read as a literal
# gate: a kind the emitter admits but the checklist forbids is a rule an
# agent's own correct draft fails, and the two ways out of that are both wrong
# -- ignore the gate, or file the other kind. So the enumeration is derived
# rather than maintained. Maintaining it is what left the checklist naming one
# kind for a whole increment after the emitter began admitting two, at a site
# two hand-driven passes over the same file both walked past.
case_docsurfaces_capture_kinds_reach_the_checklist() {
  local skill="$REPO_ROOT/skills/issue/SKILL.md" rule k n=0 missing=""
  rule="$(grep -m1 -- '^- \[ \] `type` is ' "$skill")"
  assert_nonempty "the checklist states a kind rule" "$rule"
  while IFS= read -r k; do
    [[ -n "$k" ]] || continue
    n=$((n + 1))
    printf '%s' "$rule" | grep -qF -- "\`$k\`" || missing="$missing$k "
  done < <(issue_kinds)
  assert_eq "the array was read (>= 2 kinds, got $n)" "yes" \
    "$([[ "$n" -ge 2 ]] && echo yes || echo no)"
  assert_eq "every kind the emitter admits is on the checklist" "" "${missing% }"
}

# AC: the dispatch bullet's `--type` synopsis names every kind the emitter
# admits. The capture flow deliberately does not judge the kind — the emitter
# owns that vocabulary and its refusal is the answer — so this synopsis is the
# only place the skill tells a developer which kinds exist, and a kind added to
# the array with no mention here is one nobody is told they can ask for.
case_docsurfaces_capture_kinds_reach_the_dispatch_bullet() {
  local skill="$REPO_ROOT/skills/issue/SKILL.md" line k n=0 missing=""
  line="$(grep -m1 -- '^  - `--type ' "$skill")"
  assert_nonempty "the bullet states a --type synopsis" "$line"
  while IFS= read -r k; do
    [[ -n "$k" ]] || continue
    n=$((n + 1))
    printf '%s' "$line" | grep -qF -- "$k" || missing="$missing$k "
  done < <(issue_kinds)
  assert_eq "the array was read (>= 2 kinds, got $n)" "yes" \
    "$([[ "$n" -ge 2 ]] && echo yes || echo no)"
  assert_eq "every kind the emitter admits is in the synopsis" "" "${missing% }"
}

# ─── Section: Standalone-runnable tail ───────────────────────────────────────

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  FILTER="${1:-}"
  run_discovered_cases
fi
